<?php
include_once('web-config.php');
getHeader("Home @".getAppName().".pk Instagram Shop, cute, fancy, good quality and cheap products in pakistan", "includes/header.php");
include_once('components/slider.php');
include_once('components/category-banner.php');
include_once('components/featured.php');
include_once('components/two-banners.php');
include_once('components/bestsellers.php');
include_once('components/instagram.php');
include_once('components/quick-view.php');
include_once('components/quick-shop.php');
include_once('components/mini-cart-box.php');
include_once('components/search-box.php');
include_once('components/login-box.php');
include_once('components/mobile-toolbar.php');
include_once('components/mobile-menu.php');
include_once('components/back-to-top-button.php');
include_once('components/discount-popup.php');
getFooter("includes/footer.php");
?>